adding documentation for pull request
digipolisantwerpdocumentation/status-monitoring pull request #2
Opened 2018-07-03 07:22 UTC by tom-dierckx

2018-07-04 08:15 UTC, driesdroesbeke commented
doctoc toevoegen voor inhoudsopgave

2018-07-30 07:58 UTC, PeterClaes requested changes

2018-07-30 07:58 UTC, PeterClaes commented on README.md
> +Dit document is een richtlijn naar inrichting van de health check endpoint ingebouwd op alle REST API's.
van **het** health check endpoint

2018-07-30 07:58 UTC, PeterClaes commented on README.md
> +Deze endpoint beschrijft de werking van de service. Als deze niet werkende is zullen onderstaande niveaus worden gebruikt.
**Dit** endpoint beschrijft de werking van de service. 

> Verwijder de 2e zin, die heeft geen nut.

2018-07-30 07:58 UTC, PeterClaes commented on README.md
> +degraded|de service functioneert niet meer op 100% niet kritieke systemen zijn niet bereikbaar of de applicatie verwerkt trager requests
de service functioneert niet meer op 100%, niet kritische systemen zijn niet bereikbaar of de applicatie verwerkt requests trager

2018-07-30 07:58 UTC, PeterClaes commented on README.md
> +Default zouden we deze status aanbieden naar afnemers toe, deze endpoint zou mee publiek ontsloten zijn op de API Gateway. Omdat consumers alleen geïnteresseerd zijn in of de service werkt.
Default zouden we volgende status aanbieden omdat consumers alleen willen weten of de service werkt. Dit endpoint wordt publiek mee ontsloten op de API Gateway.

2018-07-30 07:58 UTC, PeterClaes commented on README.md
> +Bepaalde niet critische systemen zijn onbeschikbaar (bijvoorbeeld logging, limiet van DB connecties is bereikt).
**k**ritische

2018-07-30 07:58 UTC, PeterClaes commented on README.md
> +Voor het continuous monitoring platform is er de components endpoint. Deze geeft een overzicht van alle afhankelijkheden en hun status.
**het** components endpoint. **Dit** geeft

2018-07-30 07:58 UTC, PeterClaes commented on README.md
> +Default supported layout van prometheus is in plain formaat.
> Onze standaard is application/json --> kan dit formaat niet worden aangeboden ? En ik zou ook niet spreken over prometheus, maar over het continuous monitoring systeem zoals in de rest van het document.

2018-07-30 07:58 UTC, PeterClaes commented on README.md
> +Flask metrics example:
> Wat is flask ? + ook opmerking ivm application/json

2018-07-30 07:58 UTC, PeterClaes commented on README.md
> +`/status/metrics`			|			X				|		X			|	Continuous Monitoring
> Wordt /status/metrics ook op de API GW gepubliceerd ? Zo ja, waarom ? Moet dit beschikbaar zijn voor consumers of enkel voor het continuous monitoring systeem ?

2018-09-18 09:20 UTC, tom-dierckx commented on README.md
> +Flask metrics example:
Flask is een web framework geschreven in Python, heb dit toegevoegd

2018-10-08 14:54 UTC, PeterClaes commented on README.md
> +Default supported layout van continuous monitoring is in prometheus plain text formaat. Beschijving van de layout is [hier][prometheus metrics format] terug te vinden.
.... plain **-/-** text formaat. Besch **-r-** ijving

2018-10-08 14:55 UTC, PeterClaes requested changes
typo

2018-10-09 09:28 UTC, tom-dierckx commented on README.md
> +Default supported layout van continuous monitoring is in prometheus plain text formaat. Beschijving van de layout is [hier][prometheus metrics format] terug te vinden.
Done

2018-10-09 10:38 UTC, PeterClaes approved these changes

2018-10-09 10:41 UTC, merged